//  ____ _                                                _     _                 ____          _         __   __                                       
// / ___| |__   ___  _ __ ___  ___   __ _ _ __ __ _ _ __ | |__ (_) ___           / ___|___   __| | ___   |  | |  |
//| |   | '_ \ / _ \| '__/ _ \/ _ \ / _` | '__/ _` | '_ \| '_ \| |/ __|  _____  | |   / _ \ / _` |/ _ (  |  | |  |
//| |___| | | | (_) | | |  __/ (_) | (_| | | | (_| | |_) | | | | | (__  |_____| | |__| (_) | (_| |  __/  |  | |  |
// \____|_| |_|\___/|_|  \___|\___/ \__, |_|  \__,_| .__/|_| |_|_|\___|          \____\___/ \__,_|\___|  |__| |__| 
//                                  |___/          |_|                                                                                          

//a GLOSSARY for Tango

// ---------------------------------------- Intro:


function new_Title () {
document.querySelector("#title1").style.display = "none";
document.querySelector("#title2").style.color = "white";
};
//new_Title ()


function Position_Zero ()  {
window.open("Improvisation_ Coordinada.html","_self")
};
//Position_Zero ()

// ---------------------------------------- Improvisation Coordenada:


var random_X = Math.floor(Math.random() * 2500);
var random_Y = Math.floor(Math.random() * 2500);
var random_x1 = Math.floor(Math.random() *2500);
var random_y1 = Math.floor(Math.random() *2500);
var random_x2 = Math.floor(Math.random() *2500);
var random_y2 = Math.floor(Math.random() *2500);


function Parella() {
  aWindow = window.open("",  "_blank", "width=250, height=250");
    anotherWindow = window.open("",  "_blank", "width=250, height=250");
}
Parella()

//function Improvised_Sequence() {

function uno() {
    aWindow.moveTo(random_X, random_Y);
    aWindow.focus();
    anotherWindow.moveTo(random_X, random_Y);
    anotherWindow.focus();

setTimeout("uno()",1500);
}

 function dos() {
    aWindow.moveTo(random_x1, random_y1);
    aWindow.focus();  
    anotherWindow.moveTo(random_y1, random_y1);
    anotherWindow.focus();
}
setTimeout("dos()",2500);

function tres() {
    aWindow.moveTo(random_x2, random_y1);
    aWindow.focus();  
    anotherWindow.moveTo(random_x2, random_y2);
    anotherWindow.focus();
}
setTimeout("tres()",3500);

function quatro() {
    aWindow.moveTo(random_x1, random_y2);
    aWindow.focus();  
    anotherWindow.moveTo(random_x1, random_y2);
    anotherWindow.focus();
}
setTimeout("quatro()",10000);

function cinco() {
    aWindow.moveTo(random_X, random_Y);
    aWindow.focus();  
    anotherWindow.moveTo(random_X, random_y1);
    anotherWindow.focus();
}
setTimeout("cinco()",11000);

function seis() {
    aWindow.moveTo( random_x1, random_y2);
    aWindow.focus();  
    anotherWindow.moveTo(random_x1, random_y2);
    anotherWindow.focus();
}
setTimeout("seis()",12000);

function sete() {
    aWindow.moveTo(random_X, random_y2);
    aWindow.focus();  
    anotherWindow.moveTo(random_X, random_y2);
    anotherWindow.focus();
}
setTimeout("sete()",13500);

function ocho() {
    aWindow.moveTo(random_x2, random_y2);
    aWindow.focus();  
    anotherWindow.moveTo(random_x2, random_y2);
    anotherWindow.focus();
}
setTimeout("ocho()",15000); 

//};


// ---------------------------------------- ON GOOGLE TRANSLATE

  function PositionZero () {
  var url = window.open('https://translate.google.com/#en/es/Hello%20World!', '_blank');
  window.location.href = url;
  url.focus();
}


var textarray = [
"Al bailar, se dialoga constantemente sin pronunciar palabra,",
"the resounding silence,",
"the silent words of Tango de-tranquilize",
"",
"A spaceless and timeless choreography",
"A complex network of (mis)understood directions and rhythms",
"A language in circulation,",
"nomadic.",
"Only two/too bodies can speak it",
"Self and Other - crossing terriories,",
"listen",
"everybody."
"Su forma universal y que esa especie venturosa tiene,",
"aunque humilde, un lugar en el universo."
];

//of walking or dancing tango together
//establishing a space where we can encounter each other
//a language that introduces you to a movement that invites you to respond 
//to a direction we initiate together
//by responding to the proposition with a counter-movement, 
//re-creating the temporal horizon of virtual possibilities 
//which all those partaking are collectively sustaining and individually assessing
//inter-action unfolds in which the operations of leading and following are constantly re-destributed
//in a micro-context, the peculiar political configuration of an a-personal ‘’leading/following” (or following leading) that provisionally displaces and de-segments the general line of inequality informing a semi-directive work relationship
//leading is more like initiating an opening, entering a gap, 
//the unfilled gaps between steps
//myriad of possibilities generated by two bodies
//I am not moving her, nor is she simply responding o me: we are beginning to move relationally, creating an interval 
//we move together




var demo_input = document.querySelector('#source')

function Improvised_Sequence_or_Phrasing() {

var rannum= Math.floor(Math.random()*textarray.length);
demo_input.value =textarray[rannum];
};

// on google translate, open the web console and let the dance begin:
//setInterval("Improvised_Sequence_or_Phrasing()", 5000) 

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

//document.querySelector('#source').style.fontSize="300px";
//document.querySelector('#source').style.width="1200px";
//document.querySelector("#source").style.lineHeight="300px";
//document.querySelector("#source").style.letterSpacing="20px";

//document.querySelector('.source-wrap').style.opacity="0.5";

//document.querySelector('body').style.transform="scale(0.5)";

//document.querySelector("body").style.writingMode="vertical-lr";
//document.querySelector("body").style.textOrientation="upright";

//document.querySelector("body").style.transform="rotateY(180deg)"

// document.querySelector("body").style.background="repeating-radial-gradient(gray, white, black 100px)";

//document.querySelector("body").style.background="repeating-linear-gradient(transparent, black 40px), repeating-linear-gradient(0.25turn, transparent, black 20px)";

function newGradient() {
  var c1 = {
        r: Math.floor(Math.random()*1),
        g: Math.floor(Math.random()*1),
        b: Math.floor(35+Math.random()*255)
      };
      var c2 = {
        r: Math.floor(0),
        g: Math.floor(Math.random()*1),
        b: Math.floor(Math.random()*255)
      };
  c1.rgb = 'rgb('+c1.r+','+c1.g+','+c1.b+')';
  c2.rgb = 'rgb('+c2.r+','+c2.g+','+c2.b+')';
  return 'repeating-linear-gradient(transparent, white, '+c1.rgb+', white, '+c2.rgb+', '+c1.rgb+', '+c2.rgb+', white, '+c2.rgb+', '+c1.rgb+', '+c2.rgb+', white, '+c2.rgb+','+c1.rgb+')';
}

function DancingFloor() {
  document.querySelector("html").style.background=newGradient();
  setTimeout(function(){DancingFloor();}, 1000);
}
//DancingFloor() 

    function rotate () {
    var centro = document.querySelector("body"),
    deg = 10;
    des_centro = setInterval(function() {
    centro.style.transform = "rotateY(" + deg + "deg)";
    deg = (deg + 10) % 360
    }, 80); 
    } 
//rotate ()


    function pause () {
    clearInterval(des_centro);
    } 
// pause ()  

function offStage () {
    document.body.innerHTML = '';
    document.head.innerHTML = '';      
}
//offStage ()

// - - - - - - - - - - - - - - - - - - - - - - - - - more:

function double ( ){
document.querySelector(".gt-cd.gt-cd-md").style.textShadow = "650px 0.1px 0.1px #000000";  
document.querySelector(".gt-cc-l").style.width= "1600px";  
}; 
//double()


function Giro() {
document.querySelector(".gt-cc-l").style.transform="rotate(7deg)"
}
//setTimeout("Giro()",8000);

function noHablar() {
document.querySelector("#gt-src-wrap").style.backgroundColor="#000000"
} 

function noEscuchar() {
document.querySelector("#gt-res-wrap").style.backgroundColor = "#000000";
} 


function Body_Language() {
document.querySelector("body").style.background = "url(http://pzwart1.wdka.hro.nl/~jo/background.gif)";  
document.querySelector("#gt-main").style.display="none";  
} 

function BlackOut(){
  document.querySelector("#gt-main").style.backgroundColor = "#000000";
};



/*var type_this = "see, I'm typing lots and lots of things magically!";
var index = 0;

window.next_letter = function() {
    if (index <= type_this.length) {
        demo_input.value = type_this.substr(0, index++);
        setTimeout("next_letter()", 50);
    }
}*/



//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

//.goog-textarea.short_text
//#result_box

// check: http://jsfiddle.net/Caut6/1/

//document.querySelector(".gt-cc-l").style.position="relative"
//document.querySelector(".gt-cc-l").style.marginTop="-100px"

//  document.querySelector("#gt-text-c").style.backgroundColor = "#000000";

//document.querySelector("#gt-text-c").style.backgroundColor = "#000000";

//document.querySelector("#gt-res-wrap").style.backgroundColor = "#000000";
//document.querySelector("#gt-main").style.display="none”;


//setTimeout(Elements_of_Chance, 1000) 
// USE::::::::: setInterval(Elements_of_Chance, 100)   and then clearInterval(number printed in the console)

//onload = function() { One();}


// ---------------------------------------- ON TIME: You can find this one at http://codepen.io/lrsbck/pen/bpjcg

// ---------------------------------------- Curtain / Movement:

.path {
  stroke-dasharray: 7000;
  stroke-dashoffset: 7000;
  animation: dash 600s linear forwards;
}

@keyframes dash {
  to {
    stroke-dashoffset: 0;
  }
}


// ---------------------------------------- Sound:


var aud = document.getElementById('my_audio1');
function sound1() { 
    aud.autoplay = true;
    aud.load();
}


var aud = document.getElementById("my_audio1");

function pauseAudio1() {
    aud.pause();
}



//------------------------------------------------------------ extra -------------------- //


//Salida()


// segunda:
function Caminata() {
  var elem = document.querySelector(".logocont");   
  var pos = 0;
  var id = setInterval(frame, 10);
  function frame() {
    if (pos == 350) {
      clearInterval(id);
    } else {
      pos++; 
      elem.style.top = pos + 'px'; 
    }
  }
}
Caminata()

function Salida() {
document.querySelector(".logocont").style.display = "none"
}
setTimeout("Salida()",8000);



document.querySelector(".srg").style.transform="rotate(180deg)"


// Up and donwn:::::

var xMax, yMax, xNeg=0, yNeg=1;

function pageScroll() {
    window.scrollBy(5 * xNeg, 5 * yNeg);
    if(xMax == window.scrollX)xNeg = xNeg * 1;
    if(yMax == window.scrollY)yNeg = xNeg * -1;
    scrolldelay = setTimeout(pageScroll,100);
    console.log(window.scrollY);
    xMax = window.scrollX;
    yMax = window.scrollY;
}
pageScroll();
//parar na console: clearTimeout(scrolldelay)

// Lado:::::

var xMax, yMax, xNeg=1, yNeg=0;

function pageScroll() {
    window.scrollBy(5 * xNeg, 5 * yNeg);
    if(xMax == window.scrollX)xNeg = xNeg * 1;
    if(yMax == window.scrollY)yNeg = xNeg * -1;
    scrolldelay = setTimeout(pageScroll,100);
    console.log(window.scrollY);
    xMax = window.scrollX;
    yMax = window.scrollY;
}
pageScroll();

// todo o Lado:::::

var xMax, yMax, xNeg=1, yNeg=0;

function pageScroll() {
    window.scrollBy(5 * xNeg, 5 * yNeg);
    if(xMax == window.scrollX)xNeg = xNeg * -1;
    if(yMax == window.scrollY)yNeg = xNeg * 1;
    scrolldelay = setTimeout(pageScroll,100);
    console.log(window.scrollY);
    xMax = window.scrollX;
    yMax = window.scrollY;
}
pageScroll();


/*— on google search: “Poética del Tango”; 
“タンゴの詩学”;  - https://www.google.com.ar/search?q=%E3%82%BF%E3%83%B3%E3%82%B4%E3%81%AE%E8%A9%A9%E5%AD%A6&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=ZzPLV6-_OYXX8gfN7ICQDA
“Poetics of Tango”;  - https://www.google.com.ar/search?q=poetics+of+Tango&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=mDPLV4LBG4XX8gfN7ICQDA
“runousoppi tango”; - https://www.google.com.ar/search?q=poesia+do+tango&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=8TPLV607hdfyB83sgJAM#q=runousoppi+tango
“poëtica van de tango”
*/
